<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="NFeRecepcaoEventoService"
  targetNamespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento"
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:tns="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento"
  xmlns:nfe="http://www.portalfiscal.inf.br/nfe"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
>

  <wsdl:types>
    <xsd:schema targetNamespace="http://www.portalfiscal.inf.br/nfe">
      <xsd:import namespace="http://www.portalfiscal.inf.br/nfe"
        schemaLocation="../xsd/envEvento_v1.00.xsd" />
      <xsd:import namespace="http://www.portalfiscal.inf.br/nfe"
        schemaLocation="../xsd/retEnvEvento_v1.00.xsd" />
    </xsd:schema>
  </wsdl:types>

  <wsdl:message name="nfeRecepcaoEventoRequest">
    <wsdl:part name="nfeDadosMsg" element="nfe:envEvento" />
  </wsdl:message>
  <wsdl:message name="nfeRecepcaoEventoResponse">
    <wsdl:part name="nfeResultMsg" element="nfe:retEnvEvento" />
  </wsdl:message>

  <wsdl:portType name="NFeRecepcaoEventoPortType">
    <wsdl:operation name="nfeRecepcaoEvento">
      <wsdl:input message="tns:nfeRecepcaoEventoRequest" />
      <wsdl:output message="tns:nfeRecepcaoEventoResponse" />
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="NFeRecepcaoEventoSoapBinding" type="tns:NFeRecepcaoEventoPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="nfeRecepcaoEvento">
      <soap:operation
        soapAction="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento/nfeRecepcaoEvento" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="NFeRecepcaoEventoService">
    <wsdl:port name="NFeRecepcaoEventoPort" binding="tns:NFeRecepcaoEventoSoapBinding">
      <soap:address
        location="https://localhost:3000/ws/nferecepcaoevento" />
    </wsdl:port>
  </wsdl:service>

</wsdl:definitions>
